# Generated by Django 3.1.5 on 2021-03-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='E200317CtValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('number_10g_0_25l_30s', models.FloatField(blank=True, db_column='10G_0.25L_30S', null=True)),
                ('number_10g_0_25l_90s', models.FloatField(blank=True, db_column='10G_0.25L_90S', null=True)),
                ('number_12_5g_0_25l_30s', models.FloatField(blank=True, db_column='12.5G_0.25L_30S', null=True)),
                ('number_12_5g_0_25l_90s', models.FloatField(blank=True, db_column='12.5G_0.25L_90S', null=True)),
                ('number_15g_0_25l_30s', models.FloatField(blank=True, db_column='15G_0.25L_30S', null=True)),
                ('number_15g_0_25l_90s', models.FloatField(blank=True, db_column='15G_0.25L_90S', null=True)),
                ('number_17_5g_0_25l_30s', models.FloatField(blank=True, db_column='17.5G_0.25L_30S', null=True)),
                ('number_17_5g_0_25l_90s', models.FloatField(blank=True, db_column='17.5G_0.25L_90S', null=True)),
                ('number_10g_0_5l_30s', models.FloatField(blank=True, db_column='10G_0.5L_30S', null=True)),
                ('number_10g_0_5l_90s', models.FloatField(blank=True, db_column='10G_0.5L_90S', null=True)),
                ('number_12_5g_0_5l_30s', models.FloatField(blank=True, db_column='12.5G_0.5L_30S', null=True)),
                ('number_12_5g_0_5l_90s', models.FloatField(blank=True, db_column='12.5G_0.5L_90S', null=True)),
                ('number_15g_0_5l_30s', models.FloatField(blank=True, db_column='15G_0.5L_30S', null=True)),
                ('number_15g_0_5l_90s', models.FloatField(blank=True, db_column='15G_0.5L_90S', null=True)),
                ('number_17_5g_0_5l_30s', models.FloatField(blank=True, db_column='17.5G_0.5L_30S', null=True)),
                ('number_17_5g_0_5l_90s', models.FloatField(blank=True, db_column='17.5G_0.5L_90S', null=True)),
                ('number_10g_0_25l_50s', models.FloatField(blank=True, db_column='10G_0.25L_50S', null=True)),
                ('number_10g_0_25l_70s', models.FloatField(blank=True, db_column='10G_0.25L_70S', null=True)),
                ('number_12_5g_0_25l_50s', models.FloatField(blank=True, db_column='12.5G_0.25L_50S', null=True)),
                ('number_12_5g_0_25l_70s', models.FloatField(blank=True, db_column='12.5G_0.25L_70S', null=True)),
                ('number_15g_0_25l_50s', models.FloatField(blank=True, db_column='15G_0.25L_50S', null=True)),
                ('number_15g_0_25l_70s', models.FloatField(blank=True, db_column='15G_0.25L_70S', null=True)),
                ('number_17_5g_0_25l_50s', models.FloatField(blank=True, db_column='17.5G_0.25L_50S', null=True)),
                ('number_17_5g_0_25l_70s', models.FloatField(blank=True, db_column='17.5G_0.25L_70S', null=True)),
                ('number_10g_0_5l_50s', models.FloatField(blank=True, db_column='10G_0.5L_50S', null=True)),
                ('number_10g_0_5l_70s', models.FloatField(blank=True, db_column='10G_0.5L_70S', null=True)),
                ('number_12_5g_0_5l_50s', models.FloatField(blank=True, db_column='12.5G_0.5L_50S', null=True)),
                ('number_12_5g_0_5l_70s', models.FloatField(blank=True, db_column='12.5G_0.5L_70S', null=True)),
                ('number_15g_0_5l_50s', models.FloatField(blank=True, db_column='15G_0.5L_50S', null=True)),
                ('number_15g_0_5l_70s', models.FloatField(blank=True, db_column='15G_0.5L_70S', null=True)),
                ('number_17_5g_0_5l_50s', models.FloatField(blank=True, db_column='17.5G_0.5L_50S', null=True)),
                ('number_17_5g_0_5l_70s', models.FloatField(blank=True, db_column='17.5G_0.5L_70S', null=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '200317 CT values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='E200317FoldChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('number_10g_0_25l_30s', models.FloatField(blank=True, db_column='10G_0.25L_30S', null=True)),
                ('number_10g_0_25l_90s', models.FloatField(blank=True, db_column='10G_0.25L_90S', null=True)),
                ('number_12_5g_0_25l_30s', models.FloatField(blank=True, db_column='12.5G_0.25L_30S', null=True)),
                ('number_12_5g_0_25l_90s', models.FloatField(blank=True, db_column='12.5G_0.25L_90S', null=True)),
                ('number_15g_0_25l_30s', models.FloatField(blank=True, db_column='15G_0.25L_30S', null=True)),
                ('number_15g_0_25l_90s', models.FloatField(blank=True, db_column='15G_0.25L_90S', null=True)),
                ('number_17_5g_0_25l_30s', models.FloatField(blank=True, db_column='17.5G_0.25L_30S', null=True)),
                ('number_17_5g_0_25l_90s', models.FloatField(blank=True, db_column='17.5G_0.25L_90S', null=True)),
                ('number_10g_0_5l_30s', models.FloatField(blank=True, db_column='10G_0.5L_30S', null=True)),
                ('number_10g_0_5l_90s', models.FloatField(blank=True, db_column='10G_0.5L_90S', null=True)),
                ('number_12_5g_0_5l_30s', models.FloatField(blank=True, db_column='12.5G_0.5L_30S', null=True)),
                ('number_12_5g_0_5l_90s', models.FloatField(blank=True, db_column='12.5G_0.5L_90S', null=True)),
                ('number_15g_0_5l_30s', models.FloatField(blank=True, db_column='15G_0.5L_30S', null=True)),
                ('number_15g_0_5l_90s', models.FloatField(blank=True, db_column='15G_0.5L_90S', null=True)),
                ('number_17_5g_0_5l_30s', models.FloatField(blank=True, db_column='17.5G_0.5L_30S', null=True)),
                ('number_17_5g_0_5l_90s', models.FloatField(blank=True, db_column='17.5G_0.5L_90S', null=True)),
                ('number_10g_0_25l_50s', models.FloatField(blank=True, db_column='10G_0.25L_50S', null=True)),
                ('number_10g_0_25l_70s', models.FloatField(blank=True, db_column='10G_0.25L_70S', null=True)),
                ('number_12_5g_0_25l_50s', models.FloatField(blank=True, db_column='12.5G_0.25L_50S', null=True)),
                ('number_12_5g_0_25l_70s', models.FloatField(blank=True, db_column='12.5G_0.25L_70S', null=True)),
                ('number_15g_0_25l_50s', models.FloatField(blank=True, db_column='15G_0.25L_50S', null=True)),
                ('number_15g_0_25l_70s', models.FloatField(blank=True, db_column='15G_0.25L_70S', null=True)),
                ('number_17_5g_0_25l_50s', models.FloatField(blank=True, db_column='17.5G_0.25L_50S', null=True)),
                ('number_17_5g_0_25l_70s', models.FloatField(blank=True, db_column='17.5G_0.25L_70S', null=True)),
                ('number_10g_0_5l_50s', models.FloatField(blank=True, db_column='10G_0.5L_50S', null=True)),
                ('number_10g_0_5l_70s', models.FloatField(blank=True, db_column='10G_0.5L_70S', null=True)),
                ('number_12_5g_0_5l_50s', models.FloatField(blank=True, db_column='12.5G_0.5L_50S', null=True)),
                ('number_12_5g_0_5l_70s', models.FloatField(blank=True, db_column='12.5G_0.5L_70S', null=True)),
                ('number_15g_0_5l_50s', models.FloatField(blank=True, db_column='15G_0.5L_50S', null=True)),
                ('number_15g_0_5l_70s', models.FloatField(blank=True, db_column='15G_0.5L_70S', null=True)),
                ('number_17_5g_0_5l_50s', models.FloatField(blank=True, db_column='17.5G_0.5L_50S', null=True)),
                ('number_17_5g_0_5l_70s', models.FloatField(blank=True, db_column='17.5G_0.5L_70S', null=True)),
            ],
            options={
                'db_table': '200317 Fold change',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='E200317Parameter',
            fields=[
                ('uuid', models.IntegerField(db_column='UUID', primary_key=True, serialize=False)),
                ('gelma_concentration', models.FloatField(db_column='gelma concentration')),
                ('cure_adhesive', models.CharField(blank=True, db_column='cure adhesive', max_length=10, null=True)),
                ('adhesive_concentration', models.FloatField(blank=True, db_column='adhesive concentration', null=True)),
                ('light_cure_time', models.IntegerField(blank=True, db_column='light cure time', null=True)),
                ('print_speed_mm_min_field', models.IntegerField(blank=True, db_column='print speed(mm/min)', null=True)),
                ('size_of_tip_g_field', models.IntegerField(blank=True, db_column='size of tip(G)', null=True)),
                ('thickness_mm_field', models.IntegerField(blank=True, db_column='thickness(mm)', null=True)),
                ('average_tensile_strength', models.FloatField(blank=True, db_column='Average Tensile Strength', null=True)),
                ('std_tensile_strength', models.FloatField(blank=True, db_column='STD Tensile Strength', null=True)),
                ('average_young_s_modulus', models.FloatField(blank=True, db_column="Average Young's Modulus", null=True)),
                ('std_young_s_modulus', models.FloatField(blank=True, db_column="STD Young's Modulus", null=True)),
            ],
            options={
                'db_table': '200317 parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='E200317Score',
            fields=[
                ('uuid', models.IntegerField(db_column='UUID', primary_key=True, serialize=False)),
                ('sample_name', models.CharField(max_length=30)),
                ('self_renewal', models.FloatField(blank=True, db_column='self-renewal', null=True)),
                ('ectoderm', models.FloatField(blank=True, db_column='Ectoderm', null=True)),
                ('mesoderm', models.FloatField(blank=True, db_column='Mesoderm', null=True)),
                ('endoderm', models.FloatField(blank=True, db_column='Endoderm', null=True)),
            ],
            options={
                'db_table': '200317 score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='E201016Parameter',
            fields=[
                ('uuid', models.IntegerField(db_column='UUID', primary_key=True, serialize=False)),
                ('gelma_concentration', models.FloatField(db_column='gelma concentration')),
                ('cure_adhesive', models.CharField(blank=True, db_column='cure adhesive', max_length=10, null=True)),
                ('adhesive_concentration', models.FloatField(blank=True, db_column='adhesive concentration', null=True)),
                ('light_cure_time', models.IntegerField(blank=True, db_column='light cure time', null=True)),
                ('print_speed_mm_min_field', models.IntegerField(blank=True, db_column='print speed(mm/min)', null=True)),
                ('size_of_tip_g_field', models.IntegerField(blank=True, db_column='size of tip(G)', null=True)),
                ('thickness_mm_field', models.IntegerField(blank=True, db_column='thickness(mm)', null=True)),
                ('average_tensile_strength', models.FloatField(blank=True, db_column='Average Tensile Strength', null=True)),
                ('std_tensile_strength', models.FloatField(blank=True, db_column='STD Tensile Strength', null=True)),
                ('average_young_s_modulus', models.FloatField(blank=True, db_column="Average Young's Modulus", null=True)),
                ('std_young_s_modulus', models.FloatField(blank=True, db_column="STD Young's Modulus", null=True)),
                ('self_renewal_discrete_field', models.CharField(blank=True, db_column='Self-renewal(discrete)', max_length=10, null=True)),
                ('ectoderm_discrete_field', models.CharField(blank=True, db_column='Ectoderm(discrete)', max_length=10, null=True)),
                ('mesoderm_discrete_field', models.CharField(blank=True, db_column='Mesoderm(discrete)', max_length=10, null=True)),
                ('endoderm_discrete_field', models.CharField(blank=True, db_column='Endoderm(discrete)', max_length=10, null=True)),
                ('self_renewal', models.FloatField(blank=True, db_column='Self-renewal', null=True)),
                ('ectoderm', models.FloatField(blank=True, db_column='Ectoderm', null=True)),
                ('mesoderm', models.FloatField(blank=True, db_column='Mesoderm', null=True)),
                ('endoderm', models.FloatField(blank=True, db_column='Endoderm', null=True)),
            ],
            options={
                'db_table': '201016 parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='E201016Score',
            fields=[
                ('uuid', models.AutoField(db_column='UUID', primary_key=True, serialize=False)),
                ('self_renewal_discrete_field', models.CharField(blank=True, db_column='Self-renewal(discrete)', max_length=10, null=True)),
                ('ectoderm_discrete_field', models.CharField(blank=True, db_column='Ectoderm(discrete)', max_length=10, null=True)),
                ('mesoderm_discrete_field', models.CharField(blank=True, db_column='Mesoderm(discrete)', max_length=10, null=True)),
                ('endoderm_discrete_field', models.CharField(blank=True, db_column='Endoderm(discrete)', max_length=10, null=True)),
                ('self_renewal', models.FloatField(blank=True, db_column='self-renewal', null=True)),
                ('ectoderm', models.FloatField(blank=True, db_column='Ectoderm', null=True)),
                ('mesoderm', models.FloatField(blank=True, db_column='Mesoderm', null=True)),
                ('endoderm', models.FloatField(blank=True, db_column='Endoderm', null=True)),
            ],
            options={
                'db_table': '201016 score',
                'managed': False,
            },
        ),
    ]
