# Generated by Django 3.1.5 on 2021-03-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_scorecardctvalues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScorecardCtValues',
        ),
    ]
