# Generated by Django 3.1.5 on 2021-05-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtValuesControl_201016',
            fields=[
                ('uuid', models.AutoField(db_column='UUID', primary_key=True, serialize=False)),
                ('actb', models.FloatField(blank=True, db_column='ACTB', null=True)),
                ('actb_1', models.FloatField(blank=True, db_column='ACTB_1', null=True)),
                ('actb_2', models.FloatField(blank=True, db_column='ACTB_2', null=True)),
                ('actb_3', models.FloatField(blank=True, db_column='ACTB_3', null=True)),
                ('ctcf', models.FloatField(blank=True, db_column='CTCF', null=True)),
                ('ep300', models.FloatField(blank=True, db_column='EP300', null=True)),
                ('smad1', models.FloatField(blank=True, db_column='SMAD1', null=True)),
            ],
            options={
                'db_table': '201016 CT values control',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtValuesMesendoderm_201016',
            fields=[
                ('uuid', models.AutoField(db_column='UUID', primary_key=True, serialize=False)),
                ('fgf4', models.FloatField(blank=True, db_column='FGF4', null=True)),
                ('gdf3', models.FloatField(blank=True, db_column='GDF3', null=True)),
                ('nppb', models.FloatField(blank=True, db_column='NPPB', null=True)),
                ('nr5a2', models.FloatField(blank=True, db_column='NR5A2', null=True)),
                ('pthlh', models.FloatField(blank=True, db_column='PTHLH', null=True)),
                ('t', models.FloatField(blank=True, db_column='T', null=True)),
            ],
            options={
                'db_table': '201016 CT values mesendoderm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtValuesMesoderm_201016',
            fields=[
                ('uuid', models.AutoField(db_column='UUID', primary_key=True, serialize=False)),
                ('abca4', models.FloatField(blank=True, db_column='ABCA4', null=True)),
                ('alox15', models.FloatField(blank=True, db_column='ALOX15', null=True)),
                ('bmp10', models.FloatField(blank=True, db_column='BMP10', null=True)),
                ('cdh5', models.FloatField(blank=True, db_column='CDH5', null=True)),
                ('cdx2', models.FloatField(blank=True, db_column='CDX2', null=True)),
                ('colec10', models.FloatField(blank=True, db_column='COLEC10', null=True)),
                ('esm1', models.FloatField(blank=True, db_column='ESM1', null=True)),
                ('fcn3', models.FloatField(blank=True, db_column='FCN3', null=True)),
                ('foxf1', models.FloatField(blank=True, db_column='FOXF1', null=True)),
                ('hand1', models.FloatField(blank=True, db_column='HAND1', null=True)),
                ('hand2', models.FloatField(blank=True, db_column='HAND2', null=True)),
                ('hey1', models.FloatField(blank=True, db_column='HEY1', null=True)),
                ('hopx', models.FloatField(blank=True, db_column='HOPX', null=True)),
                ('il6st', models.FloatField(blank=True, db_column='IL6ST', null=True)),
                ('nkx2_5', models.FloatField(blank=True, db_column='NKX2-5', null=True)),
                ('odam', models.FloatField(blank=True, db_column='ODAM', null=True)),
                ('pdgfra', models.FloatField(blank=True, db_column='PDGFRA', null=True)),
                ('plvap', models.FloatField(blank=True, db_column='PLVAP', null=True)),
                ('rgs4', models.FloatField(blank=True, db_column='RGS4', null=True)),
                ('snai2', models.FloatField(blank=True, db_column='SNAI2', null=True)),
                ('tbx3', models.FloatField(blank=True, db_column='TBX3', null=True)),
                ('tm4sf1', models.FloatField(blank=True, db_column='TM4SF1', null=True)),
            ],
            options={
                'db_table': '201016 CT values mesoderm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtValuesSelfrenewal_201016',
            fields=[
                ('uuid', models.AutoField(db_column='UUID', primary_key=True, serialize=False)),
                ('cxcl5', models.FloatField(blank=True, db_column='CXCL5', null=True)),
                ('dnmt3b', models.FloatField(blank=True, db_column='DNMT3B', null=True)),
                ('hesx1', models.FloatField(blank=True, db_column='HESX1', null=True)),
                ('ido1', models.FloatField(blank=True, db_column='IDO1', null=True)),
                ('lck', models.FloatField(blank=True, db_column='LCK', null=True)),
                ('nanog', models.FloatField(blank=True, db_column='NANOG', null=True)),
                ('pou5f1', models.FloatField(blank=True, db_column='POU5F1', null=True)),
                ('sox2', models.FloatField(blank=True, db_column='SOX2', null=True)),
                ('trim22', models.FloatField(blank=True, db_column='TRIM22', null=True)),
            ],
            options={
                'db_table': '201016 CT values selfrenewal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoldChangeEctoderm_201016',
            fields=[
                ('uuid', models.AutoField(db_column='UUID', primary_key=True, serialize=False)),
                ('cdh9', models.FloatField(blank=True, db_column='CDH9', null=True)),
                ('col2a1', models.FloatField(blank=True, db_column='COL2A1', null=True)),
                ('dmbx1', models.FloatField(blank=True, db_column='DMBX1', null=True)),
                ('drd4', models.FloatField(blank=True, db_column='DRD4', null=True)),
                ('en1', models.FloatField(blank=True, db_column='EN1', null=True)),
                ('lmx1a', models.FloatField(blank=True, db_column='LMX1A', null=True)),
                ('map2', models.FloatField(blank=True, db_column='MAP2', null=True)),
                ('myo3b', models.FloatField(blank=True, db_column='MYO3B', null=True)),
                ('nos2', models.FloatField(blank=True, db_column='NOS2', null=True)),
                ('nr2f1_nr2f2', models.FloatField(blank=True, db_column='NR2F1-NR2F2', null=True)),
                ('nr2f2', models.FloatField(blank=True, db_column='NR2F2', null=True)),
                ('olfm3', models.FloatField(blank=True, db_column='OLFM3', null=True)),
                ('papln', models.FloatField(blank=True, db_column='PAPLN', null=True)),
                ('pax3', models.FloatField(blank=True, db_column='PAX3', null=True)),
                ('pax6', models.FloatField(blank=True, db_column='PAX6', null=True)),
                ('pou4f1', models.FloatField(blank=True, db_column='POU4F1', null=True)),
                ('prkca', models.FloatField(blank=True, db_column='PRKCA', null=True)),
                ('sdc2', models.FloatField(blank=True, db_column='SDC2', null=True)),
                ('sox1', models.FloatField(blank=True, db_column='SOX1', null=True)),
                ('trpm8', models.FloatField(blank=True, db_column='TRPM8', null=True)),
                ('wnt1', models.FloatField(blank=True, db_column='WNT1', null=True)),
                ('zbtb16', models.FloatField(blank=True, db_column='ZBTB16', null=True)),
            ],
            options={
                'db_table': '201016 Fold change ectoderm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoldChangeEndoderm_201016',
            fields=[
                ('uuid', models.AutoField(db_column='UUID', primary_key=True, serialize=False)),
                ('afp', models.FloatField(blank=True, db_column='AFP', null=True)),
                ('cabp7', models.FloatField(blank=True, db_column='CABP7', null=True)),
                ('cdh20', models.FloatField(blank=True, db_column='CDH20', null=True)),
                ('cldn1', models.FloatField(blank=True, db_column='CLDN1', null=True)),
                ('cplx2', models.FloatField(blank=True, db_column='CPLX2', null=True)),
                ('elavl3', models.FloatField(blank=True, db_column='ELAVL3', null=True)),
                ('eomes', models.FloatField(blank=True, db_column='EOMES', null=True)),
                ('foxa1', models.FloatField(blank=True, db_column='FOXA1', null=True)),
                ('foxa2', models.FloatField(blank=True, db_column='FOXA2', null=True)),
                ('foxp2', models.FloatField(blank=True, db_column='FOXP2', null=True)),
                ('gata4', models.FloatField(blank=True, db_column='GATA4', null=True)),
                ('gata6', models.FloatField(blank=True, db_column='GATA6', null=True)),
                ('hhex', models.FloatField(blank=True, db_column='HHEX', null=True)),
                ('hmp19', models.FloatField(blank=True, db_column='HMP19', null=True)),
                ('hnf1b', models.FloatField(blank=True, db_column='HNF1B', null=True)),
                ('hnf4a', models.FloatField(blank=True, db_column='HNF4A', null=True)),
                ('klf5', models.FloatField(blank=True, db_column='KLF5', null=True)),
                ('lefty1', models.FloatField(blank=True, db_column='LEFTY1', null=True)),
                ('lefty2', models.FloatField(blank=True, db_column='LEFTY2', null=True)),
                ('nodal', models.FloatField(blank=True, db_column='NODAL', null=True)),
                ('phox2b', models.FloatField(blank=True, db_column='PHOX2B', null=True)),
                ('pou3f3', models.FloatField(blank=True, db_column='POU3F3', null=True)),
                ('prdm1', models.FloatField(blank=True, db_column='PRDM1', null=True)),
                ('rxrg', models.FloatField(blank=True, db_column='RXRG', null=True)),
                ('sox17', models.FloatField(blank=True, db_column='SOX17', null=True)),
                ('sst', models.FloatField(blank=True, db_column='SST', null=True)),
            ],
            options={
                'db_table': '201016 Fold change endoderm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoldChangeMesendoderm_201016',
            fields=[
                ('uuid', models.AutoField(db_column='UUID', primary_key=True, serialize=False)),
                ('fgf4', models.FloatField(blank=True, db_column='FGF4', null=True)),
                ('gdf3', models.FloatField(blank=True, db_column='GDF3', null=True)),
                ('nppb', models.FloatField(blank=True, db_column='NPPB', null=True)),
                ('nr5a2', models.FloatField(blank=True, db_column='NR5A2', null=True)),
                ('pthlh', models.FloatField(blank=True, db_column='PTHLH', null=True)),
                ('t', models.FloatField(blank=True, db_column='T', null=True)),
            ],
            options={
                'db_table': '201016 Fold change mesendoderm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoldChangeMesoderm_201016',
            fields=[
                ('uuid', models.AutoField(db_column='UUID', primary_key=True, serialize=False)),
                ('abca4', models.FloatField(blank=True, db_column='ABCA4', null=True)),
                ('alox15', models.FloatField(blank=True, db_column='ALOX15', null=True)),
                ('bmp10', models.FloatField(blank=True, db_column='BMP10', null=True)),
                ('cdh5', models.FloatField(blank=True, db_column='CDH5', null=True)),
                ('cdx2', models.FloatField(blank=True, db_column='CDX2', null=True)),
                ('colec10', models.FloatField(blank=True, db_column='COLEC10', null=True)),
                ('esm1', models.FloatField(blank=True, db_column='ESM1', null=True)),
                ('fcn3', models.FloatField(blank=True, db_column='FCN3', null=True)),
                ('foxf1', models.FloatField(blank=True, db_column='FOXF1', null=True)),
                ('hand1', models.FloatField(blank=True, db_column='HAND1', null=True)),
                ('hand2', models.FloatField(blank=True, db_column='HAND2', null=True)),
                ('hey1', models.FloatField(blank=True, db_column='HEY1', null=True)),
                ('hopx', models.FloatField(blank=True, db_column='HOPX', null=True)),
                ('il6st', models.FloatField(blank=True, db_column='IL6ST', null=True)),
                ('nkx2_5', models.FloatField(blank=True, db_column='NKX2-5', null=True)),
                ('odam', models.FloatField(blank=True, db_column='ODAM', null=True)),
                ('pdgfra', models.FloatField(blank=True, db_column='PDGFRA', null=True)),
                ('plvap', models.FloatField(blank=True, db_column='PLVAP', null=True)),
                ('rgs4', models.FloatField(blank=True, db_column='RGS4', null=True)),
                ('snai2', models.FloatField(blank=True, db_column='SNAI2', null=True)),
                ('tbx3', models.FloatField(blank=True, db_column='TBX3', null=True)),
                ('tm4sf1', models.FloatField(blank=True, db_column='TM4SF1', null=True)),
            ],
            options={
                'db_table': '201016 Fold change mesoderm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoldChangeSelfrenewal_201016',
            fields=[
                ('uuid', models.AutoField(db_column='UUID', primary_key=True, serialize=False)),
                ('cxcl5', models.FloatField(blank=True, db_column='CXCL5', null=True)),
                ('dnmt3b', models.FloatField(blank=True, db_column='DNMT3B', null=True)),
                ('hesx1', models.FloatField(blank=True, db_column='HESX1', null=True)),
                ('ido1', models.FloatField(blank=True, db_column='IDO1', null=True)),
                ('lck', models.FloatField(blank=True, db_column='LCK', null=True)),
                ('nanog', models.FloatField(blank=True, db_column='NANOG', null=True)),
                ('pou5f1', models.FloatField(blank=True, db_column='POU5F1', null=True)),
                ('sox2', models.FloatField(blank=True, db_column='SOX2', null=True)),
                ('trim22', models.FloatField(blank=True, db_column='TRIM22', null=True)),
            ],
            options={
                'db_table': '201016 Fold change selfrenewal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScorecardCtValues_201016',
            fields=[
                ('target', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('filepath', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Scorecard_CT_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('uuid', models.AutoField(db_column='UUID', primary_key=True, serialize=False)),
                ('gelma_concentration', models.FloatField(blank=True, null=True)),
                ('cure_adhesive', models.CharField(blank=True, max_length=10, null=True)),
                ('adhesive_concentration', models.FloatField(blank=True, null=True)),
                ('light_cure_time', models.IntegerField(blank=True, null=True)),
                ('groove_angle', models.IntegerField(blank=True, null=True)),
                ('maxmises', models.FloatField(blank=True, db_column='maxMises', null=True)),
                ('maxprincipal', models.FloatField(blank=True, db_column='maxPrincipal', null=True)),
                ('minprincipal', models.FloatField(blank=True, db_column='minPrincipal', null=True)),
                ('convergence', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'simulation result',
                'managed': False,
            },
        ),
    ]
